Update step06_deploy_maven.yml

diff --git a/.github/workflows/step06_deploy_maven.yml b/.github/workflows/step06_deploy_maven.yml
--- a/.github/workflows/step06_deploy_maven.yml
+++ b/.github/workflows/step06_deploy_maven.yml
@@ -2,8 +2,8 @@ name: Java CI/CD with Maven
 on:
   push:
     branches: [ "main" ]
-  pull_request:
-    branches: [ "main" ]
+  # pull_request:
+  #   branches: [ "main" ]
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -67,8 +67,19 @@ jobs:
 
       - name: Execute REMOTE_HOST Commands
         run: |  
-          ssh -i ~/private-key.pem ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "sudo fuser -k 8080/tcp || true"
-          ssh -i ~/private-key.pem ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "sudo nohup java -jar /home/${{ secrets.REMOTE_USER }}/app.jar &"
+          sudo fuser -k 8080/tcp || true
+            nohup sudo java -jar /home/${{ secrets.REMOTE_USER }}/app.jar > /home/${{ secrets.REMOTE_USER }}/app.log 2>&1 &
+            sleep 30
+            if pgrep -f 'java -jar.*app.jar' > /dev/null
+            then
+              echo 'Application started successfully'
+              exit 0
+            else
+              echo 'Application failed to start'
+              cat /home/${{ secrets.REMOTE_USER }}/app.log
+              exit 1
+            fi
+            "
           
           
     
